# Generated by Django 4.2.7 on 2023-11-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='userid',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='book',
            name='bookid',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='orderid',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Buyer'), ('3', 'Seller')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(to='books.book'),
        ),
    ]
